# Generated by Django 5.0.2 on 2025-04-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Borrowings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("V_ACCOUNT_NUMBER", models.CharField(max_length=50)),
                ("FIC_MIS_DATE", models.DateField()),
                ("V_PROD_CODE", models.CharField(max_length=50)),
                ("V_CCY_CODE", models.CharField(max_length=3)),
                ("N_EOP_BAL", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "N_INTEREST_RATE",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("V_INTEREST_TYPE", models.CharField(max_length=50)),
                ("V_INTEREST_METHOD", models.CharField(max_length=50)),
                (
                    "V_DAY_COUNT_IND",
                    models.DecimalField(decimal_places=5, max_digits=5),
                ),
                ("D_START_DATE", models.DateField()),
                ("D_BOOK_DATE", models.DateField()),
                ("D_MATURITY_DATE", models.DateField()),
                ("D_LAST_PAYMENT_DATE", models.DateField()),
                ("D_REPRICING_DATE", models.DateField()),
                ("D_VALUE_DATE", models.DateField()),
                ("N_AMRT_TERM", models.IntegerField()),
                ("V_AMRT_TERM_UNIT", models.CharField(max_length=20)),
                ("N_REMAIN_NO_OF_PMTS", models.IntegerField()),
                ("V_REPAYMENT_TYPE", models.CharField(max_length=50)),
                ("N_LRD_BALANCE", models.DecimalField(decimal_places=2, max_digits=15)),
                ("V_INT_PAYMENT_FREQUENCY_UNIT", models.CharField(max_length=20)),
                ("N_INT_PAYMENT_FREQUENCY", models.IntegerField()),
                ("V_INTEREST_TIMING_TYPE", models.CharField(max_length=50)),
                ("V_INSTRUMENT_TYPE_CD", models.CharField(max_length=50)),
            ],
            options={
                "unique_together": {("V_ACCOUNT_NUMBER", "FIC_MIS_DATE")},
            },
        ),
        migrations.CreateModel(
            name="Cards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("V_ACCOUNT_NUMBER", models.CharField(max_length=50)),
                ("FIC_MIS_DATE", models.DateField()),
                ("V_PROD_CODE", models.CharField(max_length=50)),
                ("V_CCY_CODE", models.CharField(max_length=3)),
                ("N_EOP_BAL", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "N_CURR_INTEREST_RATE",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("D_NEXT_PAYMENT_DATE", models.DateField()),
                ("V_INTEREST_TYPE", models.CharField(max_length=50)),
                ("V_DAY_COUNT_IND", models.CharField(max_length=20)),
            ],
            options={
                "unique_together": {("V_ACCOUNT_NUMBER", "FIC_MIS_DATE")},
            },
        ),
        migrations.CreateModel(
            name="Casa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("V_ACCOUNT_NUMBER", models.CharField(max_length=50)),
                ("FIC_MIS_DATE", models.DateField()),
                ("V_PROD_CODE", models.CharField(max_length=50)),
                ("V_CCY_CODE", models.CharField(max_length=3)),
                (
                    "N_EOP_BALANCE_SAVINGS",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "N_CURRENT_INT_RATE",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("V_INTEREST_TYPE", models.CharField(max_length=50)),
                ("N_INTEREST_FREQ", models.IntegerField()),
                ("V_INTEREST_FREQ_UNIT", models.CharField(max_length=20)),
                ("V_DAY_COUNT_IND", models.CharField(max_length=20)),
                ("D_ACCT_OPEN_DATE", models.DateField()),
                ("D_LAST_PAYMENT_DATE", models.DateField()),
                ("D_MATURITY_DATE", models.DateField()),
                ("N_AMRT_TERM", models.IntegerField()),
                ("V_AMRT_TERM_UNIT", models.CharField(max_length=20)),
                ("V_INSTRUMENT_TYPE_CD", models.CharField(max_length=50)),
            ],
            options={
                "unique_together": {("V_ACCOUNT_NUMBER", "FIC_MIS_DATE")},
            },
        ),
        migrations.CreateModel(
            name="Guarantees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("V_CONTRACT_CODE", models.CharField(max_length=50)),
                ("FIC_MIS_DATE", models.DateField()),
                ("V_PROD_CODE", models.CharField(max_length=50)),
                ("V_CCY_CODE", models.CharField(max_length=3)),
                (
                    "N_GUARANTEE_AMT",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("D_BOOK_DATE", models.DateField()),
            ],
            options={
                "unique_together": {("V_CONTRACT_CODE", "FIC_MIS_DATE")},
            },
        ),
        migrations.CreateModel(
            name="Investments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("V_ACCOUNT_NUMBER", models.CharField(max_length=50)),
                ("FIC_MIS_DATE", models.DateField()),
                ("V_PROD_CODE", models.CharField(max_length=50)),
                ("V_CCY_CODE", models.CharField(max_length=3)),
                ("N_EOP_BAL", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "N_INTEREST_RATE",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("D_MATURITY_DATE", models.DateField()),
                ("D_START_DATE", models.DateField()),
                ("D_NEXT_PAYMENT_DATE", models.DateField()),
                ("D_LAST_PAYMENT_DATE", models.DateField()),
                ("N_AMRT_TERM", models.IntegerField()),
                ("V_AMRT_TERM_UNIT", models.CharField(max_length=20)),
                ("V_REPAYMENT_TYPE", models.CharField(max_length=50)),
                ("V_INTEREST_TYPE", models.CharField(max_length=50)),
                ("N_INT_PAYMENT_FREQUENCY", models.IntegerField()),
                ("V_INT_PAYMENT_FREQ_UNIT", models.CharField(max_length=20)),
                (
                    "V_DAY_COUNT_IND",
                    models.DecimalField(decimal_places=5, max_digits=5),
                ),
                ("V_INSTRUMENT_TYPE_CD", models.CharField(max_length=50)),
            ],
            options={
                "unique_together": {("V_ACCOUNT_NUMBER", "FIC_MIS_DATE")},
            },
        ),
        migrations.CreateModel(
            name="LoanContracts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("V_ACCOUNT_NUMBER", models.CharField(max_length=50)),
                ("FIC_MIS_DATE", models.DateField()),
                ("V_PROD_CODE", models.CharField(max_length=50)),
                ("V_CCY_CODE", models.CharField(max_length=3)),
                ("N_EOP_BAL", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "N_CURR_INTEREST_RATE",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("D_BOOK_DATE", models.DateField()),
                ("D_MATURITY_DATE", models.DateField()),
                ("D_LAST_PAYMENT_DATE", models.DateField()),
                ("D_NEXT_PAYMENT_DATE", models.DateField()),
                ("N_AMRT_TERM", models.IntegerField()),
                ("V_AMRT_TERM_UNIT", models.CharField(max_length=20)),
                ("V_INTEREST_TYPE", models.CharField(max_length=50)),
                ("V_REPAYMENT_TYPE", models.CharField(max_length=50)),
                ("V_DAY_COUNT_IND", models.CharField(max_length=20)),
                ("N_REMAIN_NO_OF_PMTS", models.IntegerField()),
                ("V_INSTRUMENT_TYPE_CD", models.CharField(max_length=50)),
            ],
            options={
                "unique_together": {("V_ACCOUNT_NUMBER", "FIC_MIS_DATE")},
            },
        ),
    ]
