# Generated by Django 5.0.2 on 2025-06-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fsi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FirstDayProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("V_PROD_CODE", models.CharField(max_length=50)),
                ("V_CCY_CODE", models.CharField(max_length=3)),
                ("FIC_MIS_DATE", models.DateField()),
                ("V_PROD_NAME", models.CharField(max_length=100)),
                ("V_ACCOUNT_NUMBER", models.CharField(max_length=50)),
                ("N_EOP_BAL", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "V_INSTRUMENT_TYPE_CD",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "V_INTEREST_TYPE",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "N_INTEREST_RATE",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "V_DAY_COUNT_IND",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["V_PROD_CODE"], name="fsi_firstda_V_PROD__c7c22b_idx"
                    ),
                    models.Index(
                        fields=["FIC_MIS_DATE"], name="fsi_firstda_FIC_MIS_cea443_idx"
                    ),
                    models.Index(
                        fields=["V_CCY_CODE"], name="fsi_firstda_V_CCY_C_daec61_idx"
                    ),
                    models.Index(
                        fields=["V_INSTRUMENT_TYPE_CD"],
                        name="fsi_firstda_V_INSTR_720543_idx",
                    ),
                ],
                "unique_together": {("V_ACCOUNT_NUMBER", "FIC_MIS_DATE")},
            },
        ),
    ]
