# Generated by Django 5.0.2 on 2025-06-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fsi", "0002_firstdayproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="investments",
            name="N_ACCR_INT_AMT",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="loancontracts",
            name="D_LAST_PAYMENT_DATE",
            field=models.DateField(blank=True, null=True),
        ),
    ]
