# Generated by Django 5.0.2 on 2025-06-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fsi", "0003_investments_n_accr_int_amt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investments",
            name="D_LAST_PAYMENT_DATE",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="investments",
            name="D_NEXT_PAYMENT_DATE",
            field=models.DateField(blank=True, null=True),
        ),
    ]
