# Generated by Django 5.0.2 on 2025-06-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fsi", "0004_alter_investments_d_last_payment_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investments",
            name="N_AMRT_TERM",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
