# Generated by Django 5.0.2 on 2025-06-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fsi", "0005_alter_investments_n_amrt_term"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loancontracts",
            name="V_AMRT_TERM_UNIT",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
