# Generated by Django 5.0.2 on 2025-06-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fsi", "0006_alter_loancontracts_v_amrt_term_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investments",
            name="V_AMRT_TERM_UNIT",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="loancontracts",
            name="V_INTEREST_TYPE",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
