# Generated by Django 5.0.2 on 2025-06-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fsi", "0007_alter_investments_v_amrt_term_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investments",
            name="V_INTEREST_TYPE",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="loancontracts",
            name="V_DAY_COUNT_IND",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
