# Generated by Django 5.0.2 on 2025-06-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fsi", "0008_alter_investments_v_interest_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investments",
            name="N_INT_PAYMENT_FREQUENCY",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="loancontracts",
            name="N_REMAIN_NO_OF_PMTS",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
