# Generated by Django 5.0.2 on 2025-06-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fsi", "0009_alter_investments_n_int_payment_frequency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investments",
            name="V_INT_PAYMENT_FREQ_UNIT",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
