# Generated by Django 5.0.2 on 2025-06-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fsi", "0010_alter_investments_v_int_payment_freq_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investments",
            name="V_DAY_COUNT_IND",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
