# Generated by Django 5.0.2 on 2025-06-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fsi", "0011_alter_investments_v_day_count_ind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investments",
            name="N_ACCR_INT_AMT",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
    ]
