# Generated by Django 5.0.2 on 2025-06-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fsi", "0012_alter_investments_n_accr_int_amt"),
    ]

    operations = [
        migrations.AddField(
            model_name="loancontracts",
            name="V_AMRT_FREQ",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
