# Generated by Django 5.0.2 on 2025-06-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fsi", "0013_loancontracts_v_amrt_freq"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investments",
            name="D_MATURITY_DATE",
            field=models.DateField(blank=True, null=True),
        ),
    ]
