# Generated by Django 5.0.2 on 2025-06-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fsi", "0014_alter_investments_d_maturity_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investments",
            name="D_START_DATE",
            field=models.DateField(blank=True, null=True),
        ),
    ]
