# Generated by Django 5.0.2 on 2025-06-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fsi", "0015_alter_investments_d_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firstdayproduct",
            name="V_PROD_NAME",
            field=models.CharField(max_length=200),
        ),
    ]
