# Generated by Django 5.0.2 on 2025-06-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fsi", "0016_alter_firstdayproduct_v_prod_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loancontracts",
            name="D_NEXT_PAYMENT_DATE",
            field=models.DateField(blank=True, null=True),
        ),
    ]
