# Generated by Django 5.0.2 on 2025-06-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fsi", "0017_alter_loancontracts_d_next_payment_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="FsiCreditLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("V_PROD_CODE", models.CharField(max_length=50)),
                ("V_ACCOUNT_NUMBER", models.CharField(max_length=50)),
                ("N_EOP_BAL", models.DecimalField(decimal_places=5, max_digits=20)),
                ("V_CCY_CODE", models.CharField(max_length=3)),
                (
                    "N_INTEREST_RATE",
                    models.DecimalField(decimal_places=5, max_digits=7),
                ),
                ("V_AMRT_FREQ", models.CharField(max_length=1)),
                ("V_DAYS_TO_MATURITY", models.IntegerField()),
                ("FIC_MIS_DATE", models.DateField()),
                ("D_BOOK_DATE", models.DateField()),
                ("V_REPAYMENT_TYPE", models.CharField(max_length=20)),
                ("D_MATURITY_DATE", models.DateField()),
                ("D_NEXT_PAYMENT_DATE", models.DateField()),
                ("V_FACILITY_CODE", models.CharField(max_length=50)),
            ],
            options={
                "unique_together": {
                    ("V_PROD_CODE", "V_ACCOUNT_NUMBER", "FIC_MIS_DATE")
                },
            },
        ),
    ]
