# Generated by Django 5.0.2 on 2025-06-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fsi", "0018_fsicreditline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loancontracts",
            name="V_AMRT_FREQ",
            field=models.CharField(max_length=1),
        ),
    ]
