# Generated by Django 5.0.2 on 2025-06-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fsi", "0019_alter_loancontracts_v_amrt_freq"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loancontracts",
            name="N_AMRT_TERM",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
