# Generated by Django 5.0.2 on 2025-07-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fsi", "0020_alter_loancontracts_n_amrt_term"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fsicreditline",
            name="V_FACILITY_CODE",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
