# Generated by Django 4.2.23 on 2025-07-14 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alm_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arranged_cashflows',
            old_name='V_CASH_FLOW_TYPE',
            new_name='v_cash_flow_type',
        ),
    ]
