# Generated by Django 4.2.23 on 2025-07-14 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alm_app', '0002_rename_v_cash_flow_type_arranged_cashflows_v_cash_flow_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=255)),
                ('created_by', models.CharField(default='System', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_by', models.CharField(default='System', max_length=50)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'alm_Product_Filter',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('uses_behavioral_patterns', models.BooleanField(default=False)),
                ('execution_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_by', models.CharField(default='System', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_by', models.CharField(default='System', max_length=50)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('filters', models.ManyToManyField(related_name='processes', to='alm_app.productfilter')),
            ],
            options={
                'db_table': 'alm_Process',
            },
        ),
    ]
