# Generated by Django 4.2.23 on 2025-07-16 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alm_app', '0003_productfilter_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_Contractual_Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fic_mis_date', models.DateField()),
                ('process_name', models.CharField(max_length=100)),
                ('v_loan_type', models.CharField(max_length=50, null=True)),
                ('v_party_type_code', models.CharField(max_length=50, null=True)),
                ('v_prod_code', models.CharField(max_length=50)),
                ('v_product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('v_product_splits', models.CharField(blank=True, max_length=255, null=True)),
                ('v_prod_type', models.CharField(max_length=255)),
                ('v_ccy_code', models.CharField(max_length=10)),
                ('financial_element', models.CharField(max_length=50)),
                ('account_type', models.CharField(max_length=20)),
                ('v_prod_type_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('n_total_cash_flow_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('time_bucket_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alm_app.timebucketmaster')),
            ],
            options={
                'db_table': 'Report_Contractual_Base',
            },
        ),
    ]
