# Generated by Django 4.2.23 on 2025-07-16 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alm_app', '0004_report_contractual_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_contractual_base',
            name='cashflow_by_bucket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alm_app.aggregated_prod_cashflow_base'),
        ),
    ]
