# Generated by Django 4.2.23 on 2025-07-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alm_app', '0005_report_contractual_base_cashflow_by_bucket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report_contractual_base',
            old_name='n_total_cash_flow_amount',
            new_name='n_adjusted_cash_flow_amount',
        ),
        migrations.AddField(
            model_name='report_contractual_base',
            name='flow_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
