# Generated by Django 4.2.23 on 2025-07-17 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alm_app', '0006_rename_n_total_cash_flow_amount_report_contractual_base_n_adjusted_cash_flow_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timebuckets',
            options={'ordering': ['serial_number']},
        ),
        migrations.RemoveField(
            model_name='timebuckets',
            name='definition',
        ),
    ]
