# Generated by Django 4.2.23 on 2025-07-17 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alm_app', '0007_alter_timebuckets_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='behavioralpatternentry',
            old_name='order',
            new_name='bucket_number',
        ),
        migrations.RemoveField(
            model_name='behavioralpatternentry',
            name='multiplier',
        ),
        migrations.RemoveField(
            model_name='behavioralpatternentry',
            name='tenor',
        ),
    ]
