# Generated by Django 4.2.23 on 2025-07-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alm_app', '0008_rename_order_behavioralpatternentry_bucket_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stg_Exchange_Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fic_mis_date', models.DateField()),
                ('v_from_ccy_code', models.CharField(max_length=3)),
                ('v_to_ccy_code', models.CharField(max_length=3)),
                ('n_exchange_rate', models.DecimalField(decimal_places=6, max_digits=15)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Stg_Exchange_Rate',
                'ordering': ['fic_mis_date'],
                'unique_together': {('fic_mis_date', 'v_from_ccy_code', 'v_to_ccy_code')},
            },
        ),
    ]
