# Generated by Django 4.2.23 on 2025-07-18 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alm_app', '0009_stg_exchange_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stg_exchange_rate',
            name='is_active',
        ),
    ]
