# Generated by Django 4.2.23 on 2025-07-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alm_app', '0010_remove_stg_exchange_rate_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='behavioralpatternentry',
            name='pattern',
        ),
        migrations.AddField(
            model_name='behavioralpatternentry',
            name='description',
            field=models.TextField(default=-1212),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='behavioralpatternentry',
            name='v_prod_type',
            field=models.CharField(default=-1212, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BehavioralPatternConfig',
        ),
    ]
