# Generated by Django 4.2.23 on 2025-07-18 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alm_app', '0011_remove_behavioralpatternentry_pattern_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehavioralPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_prod_type', models.CharField(help_text='Product type exactly as it appears in Report tables', max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Behavioral_Pattern',
                'ordering': ['v_prod_type'],
            },
        ),
        migrations.CreateModel(
            name='BehavioralPatternSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_number', models.PositiveIntegerField()),
                ('percentage', models.DecimalField(decimal_places=3, max_digits=6)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='alm_app.behavioralpattern')),
            ],
            options={
                'db_table': 'Behavioral_Pattern_Split',
                'ordering': ['pattern', 'bucket_number'],
                'unique_together': {('pattern', 'bucket_number')},
            },
        ),
        migrations.DeleteModel(
            name='BehavioralPatternEntry',
        ),
    ]
