# Generated by Django 4.2.23 on 2025-07-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alm_app', '0012_behavioralpattern_behavioralpatternsplit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsi_loans_processing',
            name='v_facility_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
