# Generated by Django 5.0.2 on 2025-07-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alm_app', '0013_fsi_loans_processing_v_facility_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='LCRRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_date', models.DateField()),
                ('run_name', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='process',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='execution_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='fic_mis_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='process_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
