# Generated by Django 5.0.2 on 2025-07-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alm_app', '0014_lcrrun_process_end_time_process_error_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='process',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='process',
            name='execution_time',
        ),
        migrations.RemoveField(
            model_name='process',
            name='fic_mis_date',
        ),
        migrations.RemoveField(
            model_name='process',
            name='process_name',
        ),
        migrations.RemoveField(
            model_name='process',
            name='start_time',
        ),
        migrations.CreateModel(
            name='ExecutionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fic_mis_date', models.DateField()),
                ('run_number', models.IntegerField(default=1)),
                ('process_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='Running', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'alm_ExecutionHistory',
                'ordering': ['-fic_mis_date', '-run_number', 'start_time'],
                'unique_together': {('fic_mis_date', 'run_number', 'process_name')},
            },
        ),
    ]
