# Generated by Django 5.0.2 on 2025-08-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alm_app', '0015_remove_process_end_time_remove_process_error_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fic_mis_date', models.DateField(help_text='Reporting date')),
                ('v_prod_code', models.CharField(help_text='Internal product code', max_length=30)),
                ('v_prod_type', models.CharField(help_text='Product category / type', max_length=30)),
                ('v_prod_name', models.CharField(help_text='Human-readable product name', max_length=100)),
                ('n_balance', models.DecimalField(decimal_places=2, help_text='Closing balance for the day', max_digits=14)),
            ],
            options={
                'verbose_name': 'Product Balance',
                'verbose_name_plural': 'Product Balances',
                'db_table': 'product_balance',
                'ordering': ['-fic_mis_date', 'v_prod_code'],
                'unique_together': {('fic_mis_date', 'v_prod_code')},
            },
        ),
    ]
