# Generated by Django 5.0.2 on 2025-08-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alm_app', '0016_productbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbalance',
            name='n_balance',
            field=models.DecimalField(decimal_places=10, help_text='Closing balance for the day', max_digits=40),
        ),
        migrations.AlterField(
            model_name='productbalance',
            name='v_prod_name',
            field=models.CharField(help_text='Human-readable product name', max_length=200),
        ),
    ]
