# Generated by Django 5.0.2 on 2025-08-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alm_app', '0017_alter_productbalance_n_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbalance',
            name='v_prod_type',
            field=models.CharField(help_text='Product category / type', max_length=50),
        ),
    ]
