# Generated by Django 5.0.2 on 2025-08-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alm_app', '0018_alter_productbalance_v_prod_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbalance',
            name='v_to_ccy_code',
            field=models.CharField(default="hh", max_length=3),
            preserve_default=False,
        ),
    ]
