# Generated by Django 5.0.2 on 2025-08-06 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alm_app', '0019_productbalance_v_to_ccy_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbalance',
            old_name='v_to_ccy_code',
            new_name='v_ccy_code',
        ),
    ]
