# Generated by Django 5.0.2 on 2025-08-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alm_app', '0020_rename_v_to_ccy_code_productbalance_v_ccy_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stg_common_coa_master',
            name='d_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stg_common_coa_master',
            name='d_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stg_common_coa_master',
            name='fic_mis_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stg_common_coa_master',
            name='v_account_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stg_common_coa_master',
            name='v_accrual_basis_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stg_common_coa_master',
            name='v_common_coa_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stg_common_coa_master',
            name='v_common_coa_description',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='stg_common_coa_master',
            name='v_common_coa_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='stg_common_coa_master',
            name='v_rollup_signage_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
