# Generated by Django 5.0.2 on 2025-08-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alm_app', '0021_alter_stg_common_coa_master_d_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stg_product_master',
            name='f_prod_rate_sensitivity',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='stg_product_master',
            name='v_balance_sheet_category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stg_product_master',
            name='v_balance_sheet_category_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stg_product_master',
            name='v_common_coa_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stg_product_master',
            name='v_load_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stg_product_master',
            name='v_lob_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stg_product_master',
            name='v_prod_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stg_product_master',
            name='v_prod_group_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stg_product_master',
            name='v_prod_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stg_product_master',
            name='v_prod_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stg_product_master',
            name='v_prod_type_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
