# Generated by Django 5.0.2 on 2025-08-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alm_app', '0022_alter_stg_product_master_f_prod_rate_sensitivity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionhistory',
            name='process_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
