# Generated by Django 5.0.2 on 2025-09-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alm_app', '0023_alter_executionhistory_process_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='timebucketmaster',
            name='fic_mis_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='timebucketmaster',
            unique_together={('process_name', 'fic_mis_date', 'bucket_number')},
        ),
    ]
