# Generated by Django 5.0.2 on 2025-09-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alm_app', '0024_timebucketmaster_fic_mis_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stg_party_master',
            name='v_partner_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stg_party_master',
            name='v_party_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stg_party_master',
            name='v_party_type_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stg_party_master',
            name='v_party_type_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
