# Generated by Django 5.0.2 on 2025-09-01 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LCRRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_date', models.DateField()),
                ('run_name', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ASFSection',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsections', to='LCR.asfsection')),
            ],
        ),
        migrations.CreateModel(
            name='ASFItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='LCR.asfsection')),
            ],
            options={
                'unique_together': {('section', 'item_name')},
            },
        ),
        migrations.CreateModel(
            name='CashInflowSection',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('display_order', models.PositiveIntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsections', to='LCR.cashinflowsection')),
            ],
        ),
        migrations.CreateModel(
            name='CashInflowItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='LCR.cashinflowsection')),
            ],
            options={
                'unique_together': {('section', 'item_name')},
            },
        ),
        migrations.CreateModel(
            name='CashOutflowSection',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('runoff_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('display_order', models.PositiveIntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsections', to='LCR.cashoutflowsection')),
            ],
        ),
        migrations.CreateModel(
            name='CashOutflowItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='LCR.cashoutflowsection')),
            ],
            options={
                'unique_together': {('section', 'item_name')},
            },
        ),
        migrations.CreateModel(
            name='CurrencyAdjustmentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_date', models.DateField()),
                ('currency', models.CharField(max_length=10)),
                ('record_type', models.CharField(choices=[('HQLA', 'HQLA'), ('INFLOW', 'Cash Inflow'), ('OUTFLOW', 'Cash Outflow')], help_text='Source table for these totals', max_length=8)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Sum of raw amounts', max_digits=20)),
                ('total_adjusted_amount', models.DecimalField(decimal_places=2, help_text='Sum of adjusted amounts', max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['reporting_date', 'record_type', 'currency'],
                'unique_together': {('reporting_date', 'currency', 'record_type')},
            },
        ),
        migrations.CreateModel(
            name='HQLASection',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('L1', 'Level 1'), ('L2A', 'Level 2A'), ('L2B', 'Level 2B')], max_length=3)),
                ('display_order', models.PositiveIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsections', to='LCR.hqlasection')),
            ],
        ),
        migrations.CreateModel(
            name='HQLAItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='LCR.hqlasection')),
            ],
            options={
                'unique_together': {('section', 'item_name')},
            },
        ),
        migrations.CreateModel(
            name='RSFSection',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsections', to='LCR.rsfsection')),
            ],
        ),
        migrations.CreateModel(
            name='RSFItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='LCR.rsfsection')),
            ],
            options={
                'unique_together': {('section', 'item_name')},
            },
        ),
        migrations.CreateModel(
            name='ASFTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('adjusted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('reporting_date', models.DateField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='LCR.asfitem')),
            ],
            options={
                'unique_together': {('reporting_date', 'name', 'currency', 'item')},
            },
        ),
        migrations.CreateModel(
            name='CashInflowTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('adjusted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('aggregate_nominal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('adjusted_nominal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('reporting_date', models.DateField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='LCR.cashinflowitem')),
            ],
            options={
                'unique_together': {('reporting_date', 'name', 'currency', 'item')},
            },
        ),
        migrations.CreateModel(
            name='CashOutflowTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('adjusted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('aggregate_nominal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('adjusted_nominal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('reporting_date', models.DateField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='LCR.cashoutflowitem')),
            ],
            options={
                'unique_together': {('reporting_date', 'name', 'currency', 'item')},
            },
        ),
        migrations.CreateModel(
            name='HQLATable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('adjusted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('aggregate_nominal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('adjusted_nominal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('reporting_date', models.DateField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='LCR.hqlaitem')),
            ],
            options={
                'unique_together': {('reporting_date', 'name', 'currency', 'item')},
            },
        ),
        migrations.CreateModel(
            name='LCRRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_date', models.DateField()),
                ('currency', models.CharField(max_length=3)),
                ('amount_before_weights', models.DecimalField(decimal_places=2, max_digits=20)),
                ('adjusted_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('item_object_id', models.PositiveIntegerField()),
                ('item_name', models.CharField(blank=True, help_text="Snapshot of the item's name at the time of LCR", max_length=200, null=True)),
                ('section_object_id', models.PositiveIntegerField()),
                ('section_name', models.CharField(blank=True, help_text="Snapshot of the section's name at the time of LCR", max_length=200, null=True)),
                ('record_type', models.CharField(choices=[('HQLA', 'HQLA'), ('INFLOW', 'Cash Inflow'), ('OUTFLOW', 'Cash Outflow'), ('ASF', 'ASF'), ('RSF', 'RSF')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lcr_item_records', to='contenttypes.contenttype')),
                ('section_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lcr_section_records', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-reporting_date', 'currency'],
                'unique_together': {('reporting_date', 'currency', 'record_type', 'item_content_type', 'item_object_id')},
            },
        ),
        migrations.CreateModel(
            name='RSFTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('adjusted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('reporting_date', models.DateField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='LCR.rsfitem')),
            ],
            options={
                'unique_together': {('reporting_date', 'name', 'currency', 'item')},
            },
        ),
    ]
