# Generated by Django 5.0.2 on 2025-09-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asfsection',
            name='section_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashoutflowsection',
            name='runoff_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
