# Generated by Django 5.0.2 on 2025-09-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditline',
            name='d_book_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditline',
            name='d_maturity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditline',
            name='d_next_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditline',
            name='v_amrt_freq',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='creditline',
            name='v_days_to_maturity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditline',
            name='v_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='creditline',
            name='v_repayment_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='firstdayproduct',
            name='v_prod_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='d_book_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='d_last_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='d_maturity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='d_next_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='n_curr_payment_recd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='v_amrt_freq',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='v_amrt_repayment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='v_cust_ref_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='v_day_count_ind',
            field=models.CharField(blank=True, default='30/365', help_text='This column stores the accrual basis code for interest accrual calculation.', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='v_instrument_type_cd',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='v_interest_freq_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='loanpaymentschedule',
            name='n_leg_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanpaymentschedule',
            name='n_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='overdraftcontract',
            name='d_book_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='overdraftcontract',
            name='d_last_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='overdraftcontract',
            name='d_maturity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='overdraftcontract',
            name='d_next_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='overdraftcontract',
            name='n_curr_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed interest rate for the loan', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='overdraftcontract',
            name='n_curr_payment_recd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='overdraftcontract',
            name='v_amrt_freq',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='overdraftcontract',
            name='v_amrt_repayment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='overdraftcontract',
            name='v_cust_ref_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='overdraftcontract',
            name='v_day_count_ind',
            field=models.CharField(blank=True, default='30/365', help_text='This column stores the accrual basis code for interest accrual calculation.', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='overdraftcontract',
            name='v_instrument_type_cd',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
