# Generated by Django 5.0.2 on 2025-09-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staging', '0002_alter_creditline_d_book_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overdraftcontract',
            name='v_interest_freq_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
